#!/usr/bin/env python3
"""Shared, pure waypoint definitions for bike transform and revert motions."""

JOINT_NAMES = (
    'l_hip_yaw_jnt', 'l_hip_roll_jnt', 'l_hip_pitch_jnt',
    'l_knee_pitch_jnt', 'l_ankle_pitch_jnt', 'l_foot_roll_jnt',
    'r_hip_yaw_jnt', 'r_hip_roll_jnt', 'r_hip_pitch_jnt',
    'r_knee_pitch_jnt', 'r_ankle_pitch_jnt', 'r_foot_roll_jnt',
    'arm_base_yaw_jnt', 'arm_shoulder_pitch_jnt', 'arm_elbow_pitch_jnt',
    'arm_wrist_pitch_jnt', 'arm_wrist_roll_jnt',
)

SHOULDER_READY_RAD = -1.22173
SHOULDER_YAWED_SUPPORT_RAD = -1.91986
ELBOW_LIFT_RAD = 0.174533
SHOULDER_UP_RAD = SHOULDER_READY_RAD
HIP_PITCH_FOLD_LIMIT_RAD = 1.74533
DEEP_SQUAT_HIP_PITCH_RAD = 0.7764
DEEP_SQUAT_ANKLE_PITCH_RAD = 1.48353
KNEE_PITCH_FOLD_LIMIT_RAD = -2.0944
WRIST_PITCH_DOWN_RAD = -1.5708
REVERT_HIP_BACK_OFFSET_RAD = 0.15
READY_HIP_FORWARD_OFFSET_RAD = 0.0
READY_HIP_PITCH_RAD = 0.0
READY_KNEE_PITCH_RAD = -0.30
READY_ANKLE_FORWARD_OFFSET_RAD = 0.174533
READY_ANKLE_PITCH_RAD = 0.15 + READY_ANKLE_FORWARD_OFFSET_RAD
WRIST_PITCH_INDEX = JOINT_NAMES.index('arm_wrist_pitch_jnt')


def with_wrist_pitch_down(positions):
    updated = list(positions)
    updated[WRIST_PITCH_INDEX] = WRIST_PITCH_DOWN_RAD
    return tuple(updated)


def yawed_revert_arm_clearance(shoulder, wrist):
    return (
        0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
        0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
        3.14159, shoulder, ELBOW_LIFT_RAD, wrist, 0.0,
    )


BIKE_SUPPORTED = (
    0.0, 0.0, 0.0, 0.0, -1.57, 0.0,
    0.0, 0.0, 0.0, 0.0, -1.57, 0.0,
    3.14159, SHOULDER_READY_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
LEGS_STRAIGHT_SUPPORTED = (
    0.0, 0.0, 0.0, 0.0, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, 0.0, 0.0, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_READY_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
FOLDED_SUPPORTED = (
    0.0, 0.0, -HIP_PITCH_FOLD_LIMIT_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, HIP_PITCH_FOLD_LIMIT_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_YAWED_SUPPORT_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
HIP_RETURN_SUPPORTED = (
    0.0, 0.0, -HIP_PITCH_FOLD_LIMIT_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, HIP_PITCH_FOLD_LIMIT_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_YAWED_SUPPORT_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
DEEP_SQUAT_SUPPORTED = (
    0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_YAWED_SUPPORT_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
BACK_SHIFT_SUPPORTED = (
    0.0, 0.0, -0.3, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, 0.3, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_YAWED_SUPPORT_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
DEEP_SQUAT_CLAW_PITCH_DOWN = (
    0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    3.14159, SHOULDER_YAWED_SUPPORT_RAD, ELBOW_LIFT_RAD, WRIST_PITCH_DOWN_RAD, 0.0,
)
REVERT_YAWED_SHOULDER_READY = yawed_revert_arm_clearance(SHOULDER_READY_RAD, 0.0)
REVERT_AFTER_YAW_SHOULDER_READY = (
    0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, SHOULDER_READY_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
REVERT_AFTER_YAW_HIP_BACK = (
    0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD + REVERT_HIP_BACK_OFFSET_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD - REVERT_HIP_BACK_OFFSET_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, SHOULDER_READY_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
DEEP_SQUAT_ARMS_NORMAL = REVERT_AFTER_YAW_SHOULDER_READY
DEEP_SQUAT_ARMS_UP = (
    0.0, 0.0, -DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, DEEP_SQUAT_HIP_PITCH_RAD, KNEE_PITCH_FOLD_LIMIT_RAD, DEEP_SQUAT_ANKLE_PITCH_RAD, 0.0,
    0.0, SHOULDER_UP_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)
READY = (
    0.0, 0.0, -READY_HIP_PITCH_RAD - READY_HIP_FORWARD_OFFSET_RAD, READY_KNEE_PITCH_RAD, READY_ANKLE_PITCH_RAD, 0.0,
    0.0, 0.0, READY_HIP_PITCH_RAD + READY_HIP_FORWARD_OFFSET_RAD, READY_KNEE_PITCH_RAD, READY_ANKLE_PITCH_RAD, 0.0,
    0.0, SHOULDER_READY_RAD, 0.0, 0.0, 0.0,
)
HARDWARE_READY = READY
BIKE_FINAL = (
    0.0, 0.0, 0.0, 0.0, -1.57, 0.0,
    0.0, 0.0, 0.0, 0.0, -1.57, 0.0,
    3.14159, SHOULDER_READY_RAD, ELBOW_LIFT_RAD, 0.0, 0.0,
)


# Bike -> ready. While the wrist pitch returns from -90 to 0, raise the
# shoulder from -110 to -70 in one timed stage, rotate arm yaw back while
# shifting the hips rearward, recover the hip bias as the knees unfold, then
# settle into the same posture used by hardware startup.
REVERT_SEQUENCE = (
    with_wrist_pitch_down(BIKE_FINAL),
    with_wrist_pitch_down(BIKE_SUPPORTED),
    with_wrist_pitch_down(LEGS_STRAIGHT_SUPPORTED),
    with_wrist_pitch_down(HIP_RETURN_SUPPORTED),
    with_wrist_pitch_down(FOLDED_SUPPORTED),
    DEEP_SQUAT_CLAW_PITCH_DOWN,
    REVERT_YAWED_SHOULDER_READY,
    REVERT_AFTER_YAW_HIP_BACK,
    READY,
    HARDWARE_READY,
)

# Ready -> bike. Lower the shoulder while the arm base yaw rotates to 180
# degrees, then pitch the end gripper down and continue the fold.
TRANSFORM_SEQUENCE = (
    DEEP_SQUAT_ARMS_UP,
    DEEP_SQUAT_SUPPORTED,
    DEEP_SQUAT_CLAW_PITCH_DOWN,
    with_wrist_pitch_down(FOLDED_SUPPORTED),
    with_wrist_pitch_down(HIP_RETURN_SUPPORTED),
    with_wrist_pitch_down(LEGS_STRAIGHT_SUPPORTED),
    with_wrist_pitch_down(BIKE_SUPPORTED),
    with_wrist_pitch_down(BIKE_FINAL),
)
